export const doctors = [
  {
    name: "Dr. Amara Osei",
    role: "Cardiology",
    experienceYears: 14,
    years: "14 yrs experience",
    rating: 4.9,
    patients: "3,200+",
    education: "Harvard Medical School",
    languages: ["English", "French"],
    bio: "Leads the cardiac care unit with a focus on minimally invasive procedures and long-term heart health.",
  },
  {
    name: "Dr. Liam Chen",
    role: "Orthopedics",
    experienceYears: 9,
    years: "9 yrs experience",
    rating: 4.7,
    patients: "1,850+",
    education: "Johns Hopkins University",
    languages: ["English", "Mandarin"],
    bio: "Specializes in sports injuries and joint replacement surgery.",
  },
  {
    name: "Dr. Priya Nair",
    role: "Pediatrics",
    experienceYears: 11,
    years: "11 yrs experience",
    rating: 4.8,
    patients: "2,600+",
    education: "University of Toronto",
    languages: ["English", "Hindi"],
    bio: "Focuses on early childhood development and preventive care for infants and adolescents.",
  },
  {
    name: "Dr. Samuel Reyes",
    role: "Neurology",
    experienceYears: 17,
    years: "17 yrs experience",
    rating: 4.9,
    patients: "2,100+",
    education: "Stanford University",
    languages: ["English", "Spanish"],
    bio: "Treats complex neurological disorders with an emphasis on early diagnosis.",
  },
];